version: "3"

services:
  db:
    container_name: "project_db"
    image: "postgres:11.5-alpine"
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_MULTIPLE_DATABASES=project_prod,project_dev,project_test
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

volumes:
  db-data:

